name: Build and publish release assets

on:
  release:
    types: [created]

jobs:
  package_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build package
      run: script/packages/linux
      env:
        VERSION: ${{github.event.release.tag_name}}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{github.event.release.tag_name}}-linux
        path: pkg/${{github.event.release.tag_name}}/licensed-${{github.event.release.tag_name}}-linux-x64.tar.gz

  package_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build package
      run: script/packages/mac
      env:
        VERSION: ${{github.event.release.tag_name}}

    - uses: actions/upload-artifact@v2
      with:
        name: ${{github.event.release.tag_name}}-darwin
        path: pkg/${{github.event.release.tag_name}}/licensed-${{github.event.release.tag_name}}-darwin-x64.tar.gz

  build_gem:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Build gem
      run: gem build *.gemspec

    - uses: actions/upload-artifact@v2
      with:
        name: ${{github.event.release.tag_name}}-gem
        path: licensed-${{github.event.release.tag_name}}.gem

  upload_packages:
    runs-on: ubuntu-latest
    needs: [package_linux, package_mac, build_gem]

    steps:
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - name: Download linux package
      uses: actions/download-artifact@v2
      with:
        name: ${{github.event.release.tag_name}}-linux

    - name: Download macOS package
      uses: actions/download-artifact@v2
      with:
        name: ${{github.event.release.tag_name}}-darwin

    - name: Download gem
      uses: actions/download-artifact@v2
      with:
        name: ${{github.event.release.tag_name}}-gem

    - name: Publish linux package
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./licensed-${{github.event.release.tag_name}}-linux-x64.tar.gz
        asset_name: licensed-${{github.event.release.tag_name}}-linux-x64.tar.gz
        asset_content_type: application/gzip

    - name: Publish mac package
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./licensed-${{github.event.release.tag_name}}-darwin-x64.tar.gz
        asset_name: licensed-${{github.event.release.tag_name}}-darwin-x64.tar.gz
        asset_content_type: application/gzip

    - name: Publish gem to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${RUBYGEMS_API_KEY}\n" > $HOME/.gem/credentials
        gem push $GEM
      env:
        RUBYGEMS_API_KEY: ${{secrets.RUBYGEMS_AUTH_TOKEN}}
        GEM: licensed-${{github.event.release.tag_name}}.gem
